
ALTER TABLE public.organizations
  ADD COLUMN IF NOT EXISTS vat_number TEXT,
  ADD COLUMN IF NOT EXISTS vat_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS vat_rate NUMERIC DEFAULT 5,
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'AED',
  ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'UAE',
  ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'Asia/Dubai';
